# Generated by Django 4.1.1 on 2022-10-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="image",
            field=models.ImageField(
                blank=True, default="profile.png", null=True, upload_to="profile_pics"
            ),
        ),
    ]
