# Generated by Django 4.1.1 on 2022-10-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_userdata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_pics/profile.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
