# Generated by Django 4.1.1 on 2022-10-04 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_userdata_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="friends",
        ),
        migrations.AddField(
            model_name="userdata",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
