# Generated by Django 4.0 on 2021-12-26 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
