# Generated by Django 4.0 on 2021-12-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userdata_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdata',
            options={'ordering': ['upload_at']},
        ),
    ]
