# Generated by Django 4.1.1 on 2022-10-04 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_userdata_following_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="followers",
            field=models.ManyToManyField(
                related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
