# Generated by Django 4.0 on 2021-12-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_postdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdata',
            options={'ordering': ['-upload_at']},
        ),
    ]
