# Generated by Django 4.1.1 on 2022-10-08 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_userdata_followers_delete_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="followers",
            field=models.ManyToManyField(
                related_name="followers_obj", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
