# Generated by Django 4.1.1 on 2022-10-03 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postdata",
            name="user_like",
            field=models.ManyToManyField(
                blank=True, related_name="posts_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
